FROM ubuntu:16.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update

# Imagemagick requirements
RUN apt-get install -y wget build-essential checkinstall libx11-dev libxext-dev zlib1g-dev libpng12-dev libjpeg-dev \
    libfreetype6-dev libxml2-dev libopenexr-dev automake autoconf libfftw3-3 openexr liblcms2-dev libwebp-dev \
    imagemagick

RUN wget http://www.imagemagick.org/download/releases/ImageMagick-6.9.11-24.tar.gz && \
    export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/ && \
    tar xvf ImageMagick-6.9.11-24.tar.gz && \
    cd ImageMagick-6.9.11-24 && \
    ./configure --without-x --with-quantum-depth=8 && \
    make -j4 && make install

# mod-dims requirements
RUN apt-get install -y checkinstall automake libtool autoconf git \
    apache2 apache2-dev libcurl4-openssl-dev libfreetype6-dev \
    libopenexr-dev libxml2-dev libtiff5-dev liblcms2-dev \
    pkg-config libssl-dev libpangocairo-1.0-0

ENV TZ=America/New_York
ENV LSB_RELEASE=xenial
ENV PKG_REQUIRES="imagemagick,libcurl3,libpangocairo-1.0-0"

RUN a2enmod headers rewrite ssl proxy proxy_http
RUN a2dismod -f deflate
RUN a2disconf other-vhosts-access-log
RUN echo "export PS1='[mod-dims dev:\w]\\$ '" >> /root/.bashrc

COPY dims.conf /etc/apache2/mods-enabled/dims.conf

COPY entrypoint-dev.sh /
ENTRYPOINT /entrypoint-dev.sh
RUN chmod +x /entrypoint-dev.sh

EXPOSE 80 443