/*
 * Copyright 2009 AOL LLC 
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at 
 *         
 *         http://www.apache.org/licenses/LICENSE-2.0 
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

#ifndef _MOD_DIMS_H
#define _MOD_DIMS_H

#include <apr_strings.h>
#include <apr_file_io.h>
#include <apr_file_info.h>
#include <apr_atomic.h>
#include <apr_queue.h>
#include <apr_base64.h>
#include <apr_escape.h>
#include <apr_lib.h>

#include <httpd.h>
#include <http_core.h>
#include <http_config.h>
#include <http_request.h>
#include <http_log.h>
#include <http_protocol.h>

#include <MagickWand/MagickWand.h>

#include <curl/curl.h>
#include <stdint.h>

/* The version httpd reports and the status handler prints. Generated by
 * CMake from the project() version and the git commit. */
#include "version.h"

/* How a request ended. These do not combine: every use is == or !=. */
typedef enum {
    /* Leave the status already on the request alone. Only dims_cleanup reads
     * this, when it is reporting a failure that set the status itself. */
    DIMS_IGNORE = -1,

    DIMS_SUCCESS = 0,
    DIMS_FAILURE,
    DIMS_DOWNLOAD_TIMEOUT,
    DIMS_IMAGEMAGICK_TIMEOUT,
    DIMS_BAD_CLIENT,
    DIMS_BAD_URL,
    DIMS_BAD_ARGUMENTS,
    DIMS_HOSTNAME_NOT_IN_WHITELIST,
    DIMS_FILE_NOT_FOUND,

    /* The network guard refused the target. */
    DIMS_NETWORK_REFUSED
} dims_status_t;

/* How a multi-frame source is handled. Set from DimsAnimatedImages. */
typedef enum {
    /* Skip every command and return the source unchanged. */
    DIMS_ANIMATED_PASSTHROUGH = 0,

    /* Run the commands over every frame. */
    DIMS_ANIMATED_TRANSFORM
} dims_animated_mode;

/* Which endpoint a request arrived at. */
typedef enum {
    DIMS_SCHEME_LEGACY = 0,
    DIMS_SCHEME_DIMS5
} dims_scheme;

/* How a failure at the origin reaches the caller. Set from
 * DimsOriginStatusMode. */
typedef enum {
    /* Report whatever the origin said. */
    DIMS_ORIGIN_STATUS_FORWARD = 0,

    /* Report one of three: 404 for a missing source, 504 for a timeout, 502
     * for every other origin failure. */
    DIMS_ORIGIN_STATUS_MAP
} dims_origin_status_mode;

/* The HTTP status a dims_status_t maps to, and a short reason for the log. */
int dims_http_status(int status);
const char *dims_status_name(int status);

typedef struct dims_request_rec dims_request_rec;
typedef struct dims_config_rec dims_config_rec;
typedef struct dims_client_config_rec dims_client_config_rec;
typedef struct {
    char *data;
    size_t size;
    size_t used;
    long response_code;

    /* Zero means no limit. Set from DimsMaxSourceBytes. */
    size_t max_bytes;
    int exceeded_limit;
} dims_image_data_t;

/* One command from the request path: a name and its arguments. */
typedef struct {
    char *name;
    char *args;
} dims_command;

/*
 * The status a failure at the origin reaches the caller with, or zero when the
 * failure did not come from the origin or the mode is forward. Zero leaves the
 * caller's own mapping in charge.
 */
int dims_origin_status(dims_request_rec *d);

typedef apr_status_t(dims_operation_func) (dims_request_rec *, char *args, const char **err);

dims_operation_func 
    dims_strip_operation,
    dims_resize_operation,
    dims_crop_operation,
    dims_thumbnail_operation,
    dims_sharpen_operation,
    dims_quality_operation,
    dims_format_operation,
    dims_legacy_thumbnail_operation,
    dims_brightness_operation,
    dims_flipflop_operation,
    dims_sepia_operation,
    dims_grayscale_operation,
    dims_autolevel_operation,
    dims_rotate_operation,
    dims_invert_operation,
    dims_watermark_operation,
    dims_legacy_crop_operation;

struct dims_config_rec {
    int download_timeout;
    int imagemagick_timeout;

    apr_table_t *whitelist;
    apr_hash_t *clients;
    apr_table_t *ignore_default_output_format;

    char *no_image_url;
    long no_image_expire;
    long default_expire;
    int strip_metadata;
    float optimize_resize;
    int include_disposition;
    int disable_encoded_fetch;
    char *default_output_format;

    MagickSizeType area_size;
    MagickSizeType memory_size;
    MagickSizeType map_size;
    MagickSizeType disk_size;

    /* Largest source image to accept, in bytes. Zero means no limit. */
    size_t max_source_bytes;

    /* Whether a fetch may reach a private address. Set from
     * DimsAllowPrivateAddresses. Loopback and link local are refused whatever
     * this holds. */
    int allow_private_addresses;

    /* Whether the allowlist applies to a signed request. Set from
     * DimsAllowlistSigned: 0 logs what it would refuse, 1 refuses. */
    int allowlist_signed;

    /* How a failure at the origin reaches the caller. Set from
     * DimsOriginStatusMode. */
    int origin_status_mode;

    /* Whether the status handler prints the component versions. Set from
     * DimsStatusVerbose. */
    int status_verbose;

    /* Whether the module serves /metrics. Set from DimsMetricsEnabled. */
    int metrics_enabled;

    /* Bounds on the overlay cache. Zero turns either off. Set from
     * DimsOverlayCacheMaxEntries and DimsOverlayCacheMaxAge. */
    int overlay_cache_max_entries;
    long overlay_cache_max_age;

    /* The key /dims5/ signatures are checked against. Set from
     * DimsSigningKey. */
    const char *signing_key;

    /* The colour a generated error image is filled with. Set from
     * DimsErrorBackground. */
    const char *error_background;

    /* How a multi-frame source is handled. Set from DimsAnimatedImages. */
    int animated_mode;

    /* Where the ICC profiles live. Set from DimsProfileDir. */
    const char *profile_dir;

    const char *encryption_algorithm;
    long max_expiry_period;
    char *default_image_prefix;

    char *user_agent_override;
    int user_agent_enabled;
};

struct dims_client_config_rec {
    char *id;
    char *no_image_url;
    int cache_control_max_age;
    int edge_control_downstream_ttl;
    int trust_src;
    int min_src_cache_control;
    int max_src_cache_control;
    char *secret_key;
};

struct dims_request_rec {
    request_rec *r;

    apr_pool_t *pool;

    MagickWand *wand;

    /* Client ID of this request. */
    char *client_id;

    /* The URL to the image being manipulated. */
    char *image_url;
    int use_no_image;

    /* Which endpoint served this, as a dims_endpoint_t. */
    int endpoint;

    /* Slots in the metrics format table, or -1 before the format is known. */
    int source_format_index;
    int output_format_index;

    /* The URL to the NOIMAGE image in case of failures. */
    char *no_image_url;

    /* The filename if this is a local request. */
    char *filename;

    /* The unparsed commands (resize, crop, etc). */
    char *unparsed_commands;

    /* The commands parsed once into name and argument pairs. */
    apr_array_header_t *commands;

    /* The original image size in bytes. */
    long original_image_size;

    /* The sample factor for optimizing resizing. */
    float optimize_resize;

    /* The global configuration. */
    dims_config_rec *config;

    /* The client specific configuration, if available. */
    dims_client_config_rec *client_config;

    /* The cache headers from the downloaded image. */
    char *cache_control;
    char *edge_control;
    char *last_modified;
    char *etag;
    char *request_hash;

    /* The current status of this request.  If downloading
     * or manipulating the image times out this will
     * be set to DIMS_*_TIMEOUT.  If everything is ok it will
     * be set to DIMS_SUCCESS.
     */
    apr_status_t status;

    /* The HTTP status code from fetching the original image */
    apr_status_t fetch_http_status;

    /* Time this request started.  Used for statistics. */
    apr_time_t start_time;
    apr_time_t download_time;
    apr_time_t imagemagick_time;
    
    /* Use a whitelist, or use a secret key passed on the URI */
    int use_secret_key;

    /* Which endpoint this request arrived at. */
    int scheme;

    /* Whether the allowlist follows this fetch to every redirect hop. */
    int net_apply_allowlist;

    /* What the network guard refused, as a dims_net_result. Zero means it
     * refused nothing. */
    int net_refusal;

    /* Should Content-Disposition header bet set. */
    int send_content_disposition;
    char *content_disposition_filename;
};

#endif
